-- Schema inicial PostgreSQL para Supabase.
-- Execute este arquivo primeiro, no SQL Editor do projeto Supabase vazio.

CREATE TABLE usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  telefone VARCHAR(30),
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_usuarios_email UNIQUE (email)
);

CREATE TABLE negocios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL,
  nome VARCHAR(150) NOT NULL,
  slug_publico VARCHAR(160) NOT NULL,
  descricao TEXT,
  telefone VARCHAR(30),
  endereco VARCHAR(255),
  cidade VARCHAR(100) DEFAULT 'Cubatao',
  horario_abertura TIME NOT NULL DEFAULT TIME '08:00:00',
  horario_fechamento TIME NOT NULL DEFAULT TIME '18:00:00',
  intervalo_agendamento_minutos INTEGER NOT NULL DEFAULT 30,
  dias_funcionamento JSONB,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_negocios_slug_publico UNIQUE (slug_publico),
  CONSTRAINT fk_negocios_usuario FOREIGN KEY (usuario_id)
    REFERENCES usuarios (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_negocios_intervalo_agendamento
    CHECK (intervalo_agendamento_minutos > 0),
  CONSTRAINT chk_negocios_horario_funcionamento
    CHECK (horario_fechamento > horario_abertura),
  CONSTRAINT chk_negocios_dias_funcionamento_array
    CHECK (dias_funcionamento IS NULL OR jsonb_typeof(dias_funcionamento) = 'array')
);

CREATE TABLE servicos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id INTEGER NOT NULL,
  nome VARCHAR(120) NOT NULL,
  descricao TEXT,
  duracao_minutos INTEGER NOT NULL,
  preco NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_servicos_negocio FOREIGN KEY (negocio_id)
    REFERENCES negocios (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_servicos_duracao CHECK (duracao_minutos > 0),
  CONSTRAINT chk_servicos_preco CHECK (preco >= 0)
);

CREATE TABLE profissionais (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id INTEGER NOT NULL,
  nome VARCHAR(120) NOT NULL,
  telefone VARCHAR(30),
  email VARCHAR(180),
  especialidade VARCHAR(120),
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_profissionais_negocio FOREIGN KEY (negocio_id)
    REFERENCES negocios (id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE agendamentos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id INTEGER NOT NULL,
  servico_id INTEGER NOT NULL,
  profissional_id INTEGER NOT NULL,
  cliente_nome VARCHAR(120) NOT NULL,
  cliente_telefone VARCHAR(30) NOT NULL,
  cliente_email VARCHAR(180),
  data_hora_inicio TIMESTAMP NOT NULL,
  data_hora_fim TIMESTAMP NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'confirmado',
  observacoes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_agendamentos_negocio FOREIGN KEY (negocio_id)
    REFERENCES negocios (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_agendamentos_servico FOREIGN KEY (servico_id)
    REFERENCES servicos (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_agendamentos_profissional FOREIGN KEY (profissional_id)
    REFERENCES profissionais (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_agendamentos_periodo CHECK (data_hora_fim > data_hora_inicio),
  CONSTRAINT chk_agendamentos_status
    CHECK (status IN ('pendente', 'confirmado', 'cancelado', 'concluido'))
);

CREATE INDEX idx_usuarios_ativo ON usuarios (ativo);
CREATE INDEX idx_negocios_usuario_id ON negocios (usuario_id);
CREATE INDEX idx_negocios_ativo ON negocios (ativo);
CREATE INDEX idx_servicos_negocio_id ON servicos (negocio_id);
CREATE INDEX idx_servicos_negocio_ativo ON servicos (negocio_id, ativo);
CREATE INDEX idx_profissionais_negocio_id ON profissionais (negocio_id);
CREATE INDEX idx_profissionais_negocio_ativo ON profissionais (negocio_id, ativo);
CREATE INDEX idx_agendamentos_negocio_id ON agendamentos (negocio_id);
CREATE INDEX idx_agendamentos_servico_id ON agendamentos (servico_id);
CREATE INDEX idx_agendamentos_profissional_id ON agendamentos (profissional_id);
CREATE INDEX idx_agendamentos_negocio_inicio ON agendamentos (negocio_id, data_hora_inicio);
CREATE INDEX idx_agendamentos_profissional_periodo
  ON agendamentos (profissional_id, data_hora_inicio, data_hora_fim);
CREATE INDEX idx_agendamentos_profissional_status_periodo
  ON agendamentos (profissional_id, status, data_hora_inicio, data_hora_fim);

CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE agendamentos
  ADD CONSTRAINT ex_agendamentos_profissional_periodo_ativo
  EXCLUDE USING gist (
    profissional_id WITH =,
    tsrange(data_hora_inicio, data_hora_fim, '[)') WITH &&
  )
  WHERE (status IN ('pendente', 'confirmado'));

CREATE OR REPLACE FUNCTION atualizar_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_usuarios_updated_at BEFORE UPDATE ON usuarios
  FOR EACH ROW EXECUTE FUNCTION atualizar_updated_at();
CREATE TRIGGER trg_negocios_updated_at BEFORE UPDATE ON negocios
  FOR EACH ROW EXECUTE FUNCTION atualizar_updated_at();
CREATE TRIGGER trg_servicos_updated_at BEFORE UPDATE ON servicos
  FOR EACH ROW EXECUTE FUNCTION atualizar_updated_at();
CREATE TRIGGER trg_profissionais_updated_at BEFORE UPDATE ON profissionais
  FOR EACH ROW EXECUTE FUNCTION atualizar_updated_at();
CREATE TRIGGER trg_agendamentos_updated_at BEFORE UPDATE ON agendamentos
  FOR EACH ROW EXECUTE FUNCTION atualizar_updated_at();
