-- Governança de privacidade: transparência, canal do titular e retenção.
-- A execução deve ocorrer pelo migration runner do projeto.

ALTER TABLE usuarios
  ADD COLUMN documentos_aceitos_em TIMESTAMPTZ,
  ADD COLUMN versao_documentos_aceita VARCHAR(40);

ALTER TABLE negocios
  ADD COLUMN contato_privacidade VARCHAR(180);

ALTER TABLE agendamentos
  ALTER COLUMN cliente_telefone DROP NOT NULL,
  ADD COLUMN aviso_privacidade_versao VARCHAR(40);

CREATE TABLE solicitacoes_lgpd (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id INTEGER,
  tipo VARCHAR(30) NOT NULL,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL,
  mensagem VARCHAR(2000),
  status VARCHAR(20) NOT NULL DEFAULT 'recebida',
  concluida_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_solicitacoes_lgpd_negocio FOREIGN KEY (negocio_id)
    REFERENCES negocios (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_solicitacoes_lgpd_tipo
    CHECK (tipo IN ('acesso', 'correcao', 'eliminacao', 'portabilidade', 'informacao', 'revogacao', 'oposicao')),
  CONSTRAINT chk_solicitacoes_lgpd_status
    CHECK (status IN ('recebida', 'em_analise', 'concluida', 'recusada')),
  CONSTRAINT chk_solicitacoes_lgpd_conclusao
    CHECK ((status IN ('concluida', 'recusada')) = (concluida_at IS NOT NULL))
);

CREATE INDEX idx_solicitacoes_lgpd_status_created_at
  ON solicitacoes_lgpd (status, created_at);
CREATE INDEX idx_solicitacoes_lgpd_negocio_id
  ON solicitacoes_lgpd (negocio_id);

CREATE TRIGGER trg_solicitacoes_lgpd_updated_at BEFORE UPDATE ON solicitacoes_lgpd
  FOR EACH ROW EXECUTE FUNCTION atualizar_updated_at();

ALTER TABLE solicitacoes_lgpd ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE solicitacoes_lgpd FROM PUBLIC;
REVOKE ALL PRIVILEGES ON SEQUENCE solicitacoes_lgpd_id_seq FROM PUBLIC;

DO $privacy_governance$
DECLARE
  protected_role text;
BEGIN
  FOR protected_role IN
    SELECT rolname
    FROM pg_catalog.pg_roles
    WHERE rolname IN ('anon', 'authenticated', 'service_role')
  LOOP
    EXECUTE format(
      'REVOKE ALL PRIVILEGES ON TABLE public.solicitacoes_lgpd FROM %I',
      protected_role
    );
    EXECUTE format(
      'REVOKE ALL PRIVILEGES ON SEQUENCE public.solicitacoes_lgpd_id_seq FROM %I',
      protected_role
    );
  END LOOP;
END;
$privacy_governance$;
